#!/usr/bin/env npx ts-node
/**
 * Seed Test Tenant Script — Production-Ready
 * 
 * Idempotently creates test tenant, roles, permissions, and users for E2E tests.
 * Outputs environment variables for use in test runs.
 *
 * Usage:
 *   source .env.test && npx ts-node scripts/seed-test-tenant.ts
 *   # or
 *   npm run seed:test
 */

import {
    setupTestContext,
    validateTestEnvironment,
    TestContext
} from '../tests/utils/auth';

// =============================================================================
// Configuration
// =============================================================================

const TEST_SLUG = process.env.E2E_TENANT_SLUG ?? 'e2e-primary';
const OUTPUT_ENV_FILE = process.env.OUTPUT_ENV_FILE ?? '.env.test.local';

// =============================================================================
// Main
// =============================================================================

async function main(): Promise<void> {
    console.log('🌱 XalaBaaS Test Tenant Seeder\n');
    console.log('─'.repeat(60));

    // Validate environment
    try {
        validateTestEnvironment();
        console.log('✅ Environment validated');
    } catch (error) {
        console.error(`❌ ${(error as Error).message}`);
        process.exit(1);
    }

    // Setup test context
    console.log(`\n📦 Setting up test context for slug: ${TEST_SLUG}`);

    let context: TestContext;
    try {
        context = await setupTestContext(TEST_SLUG);
    } catch (error) {
        console.error(`❌ Failed to setup test context: ${(error as Error).message}`);
        process.exit(1);
    }

    // Output summary
    console.log('\n✅ Test Context Created:');
    console.log('─'.repeat(60));
    console.log(`  Tenant ID:     ${context.tenant.id}`);
    console.log(`  Tenant Slug:   ${context.tenant.slug}`);
    console.log(`  Admin User ID: ${context.adminUser.id}`);
    console.log(`  Admin Email:   ${context.adminUser.email}`);
    console.log(`  Admin Role ID: ${context.adminRole.id}`);
    console.log(`  Member Role:   ${context.memberRole.id}`);

    // Output environment variables
    console.log('\n📋 Environment Variables:');
    console.log('─'.repeat(60));

    const envVars = `
# Test context generated by seed-test-tenant.ts
# Generated at: ${new Date().toISOString()}

E2E_TENANT_ID=${context.tenant.id}
E2E_TENANT_SLUG=${context.tenant.slug}
E2E_USER_ID=${context.adminUser.id}
E2E_USER_EMAIL=${context.adminUser.email}
E2E_TOKEN=${context.adminUser.accessToken}
E2E_ADMIN_ROLE_ID=${context.adminRole.id}
E2E_MEMBER_ROLE_ID=${context.memberRole.id}
`.trim();

    console.log(envVars);

    // Write to file
    const fs = await import('fs');

    try {
        // Append to existing .env.test or create new
        if (fs.existsSync('.env.test')) {
            const existing = fs.readFileSync('.env.test', 'utf-8');

            // Remove old E2E_* lines
            const filtered = existing
                .split('\n')
                .filter(line => !line.startsWith('E2E_'))
                .join('\n');

            fs.writeFileSync('.env.test', filtered.trim() + '\n\n' + envVars + '\n');
            console.log('\n✅ Updated .env.test with test context');
        } else {
            fs.writeFileSync('.env.test', envVars + '\n');
            console.log('\n✅ Created .env.test with test context');
        }
    } catch (error) {
        console.warn(`⚠️ Could not write .env.test: ${(error as Error).message}`);
        console.log('\nCopy the environment variables above manually.');
    }

    // Usage instructions
    console.log('\n🚀 Ready to run tests:');
    console.log('─'.repeat(60));
    console.log('  source .env.test');
    console.log('  ./scripts/test.sh all');
    console.log('');
}

// =============================================================================
// Run
// =============================================================================

main()
    .then(() => {
        console.log('✅ Seed complete\n');
        process.exit(0);
    })
    .catch((error) => {
        console.error(`\n❌ Seed failed: ${error.message}`);
        process.exit(1);
    });
